'use client';
import './globals.css'
import { useState } from 'react';
import { NavBar, HamBtn } from "@/components/navBar";

// export const metadata = {
//   title: 'Marsmorph',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  
  const [showDropdown, setShowDropdown] = useState(false);
  return (
    <html lang="en">
      <body className='bg-black text-white -z-10'>
      {children}
      <div className=" absolute right-0 h-full top-0 w-full overflow-hidden">
        <div className="z-30 absolute right-0 w-fit m-10 hover:cursor-pointer select-none" onClick={() => setShowDropdown(!showDropdown)}>
          <HamBtn />
        </div>
        <div className={`z-20 backdrop-blur-xl absolute h-full right-0 top-0 ${showDropdown ? 'translate-x-0 opacity-100' : 'translate-x-full opacity-0'} transition-all`}>
          <NavBar />
        </div>
      </div>
      </body>
    </html>
  )
}
