import './globals.css'

export const metadata = {
  title: 'Marsmorph',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='bg-black text-white -z-10'>
        {children}
        </body>
    </html>
  )
}
